version: '3.8'

services:
 mysql:
  platform: linux/x86_64
  image: mysql
  ports:
    - 3306:3306
  expose:
    - '3306'
  environment:
    MYSQL_DATABASE: 'madness'
    MYSQL_ROOT_PASSWORD: 'root'
  volumes:
      - ./data:/var/lib/mysql
 api:
  build:
    context: ./
    dockerfile: ./api/Dockerfile
  links:
    - mysql
  ports:
  - 5000:5000
  environment:
  - FLASK_APP=utils/app.py
  - FLASK_ENV=development
  volumes:
  - "./api:/api"

volumes:
  mysql:
  mysql_config:

